tcc/urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
admin.autodiscover()
from Automation.tcc.models import *


urlpatterns = patterns('Automation.tcc.views',
    (r'^index/$', 'index1'),
    (r'^catalog/$', 'material'),
    (r'^previous/$', 'previous'),
    (r'^addprofile/$', 'profile'),
    (r'^performa/$', 'performa'),
    (r'^rate/$', 'rate'),
    (r'^performa/$', 'performa'),
    (r'^addjob/$', 'selectfield'),
    (r'^select/$', 'select'),
    (r'^save/$', 'add_job'),
    (r'^prev/$','previous'),
    (r'^transport/$', 'transport'),
    (r'^transportbill/$', 'transport_bill'),
    (r'^jobok/$', 'job_ok'),
    (r'^bill/$', 'bill'),
    (r'^receipt/$','receipt_report'),
    (r'^gen_report/$','gen_report'),
    (r'^report/$','rep'),
    (r'^map/$', 'distance'),
    (r'^save_susp/$', 'suspence'),
    (r'^g_report/$', 'g_report'),
    (r'^add_suspence/$', 'add_suspence'),
    (r'^job_submit/$', 'job_submit'),
    (r'^suspenceclearance/$', 'suspence_clearance'),
    (r'^search/$', 'search')
   
)

urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    (r'^$', direct_to_template,
                    { 'template': 'index.html' }, 'index'),
    (r'^hello', direct_to_template,
                    { 'template': 'job_ok.html' }, ),
    (r'^tcc11_12/', include('Automation.tcc.urls')),
    

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
    (r'', include('gmapi.urls.media')),
    (r'^accounts/', include('registration.urls')),
   
)

tcc/models.py
"""
Automation Model Module
 
This contains all of the definitions for the model of the Testing & Consultancy Cell Automation,
including the tables, classes and mappers.
 
"""

from django.db import models
from django.forms import ModelForm, TextInput, ModelChoiceField
import datetime
from django import forms
from Automation.tcc.choices import *
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.db.models import Max ,Q, Sum
from django.forms.fields import DateField, ChoiceField, MultipleChoiceField
from tagging.fields import TagField
from tagging.models import Tag
from django.contrib.sessions.models import Session

class Report(models.Model):
	"""
	Define Client Report Form to reterive any Report Information,
	when we fill Job Number and type of Report Store in Database
	"""
	name = models.CharField(max_length=50)

	def __unicode__(self):
        	return self.name

class UserProfile(models.Model):
    # This field is required.
        user = models.ForeignKey(User)

    # Other fields here
        name = models.CharField(max_length=255,)
	address_1 =models.CharField(max_length=255 ,blank=True )
	address_2 =models.CharField(max_length=255, blank=True )
	city =models.CharField(max_length=255,blank=True)
	pin_code = models.IntegerField(null=True)
	state=models.CharField(max_length=30, blank = True,choices=STATES_CHOICES)
	website =models.URLField(blank=True)
	contact_no =models.CharField(max_length=25,blank=True)
	type_of_organisation = models.CharField(max_length=20,choices=ORGANISATION_CHOICES)

	def __unicode__(self):
        	return self.name


class UserProfileForm(ModelForm):
	class Meta :
		model = UserProfile
		exclude= ['user']	

def create_user_profile(sender, instance, created, **kwargs):
    if created:
        created = UserProfile.objects.get_or_create(user=instance)
post_save.connect(create_user_profile, sender=User)
 

class Auto_number(models.Model):
	id = models.AutoField(primary_key=True)
	job_no = models.IntegerField(unique = True)

class Lab(models.Model):
	code = models.CharField(max_length=5)
	name = models.CharField(max_length=300)
	tags = TagField()

	def __unicode__(self):
        	return self.name

	def get_tags(self):
        	return Tag.objects.get_for_object(self) 


class DynamicChoiceField(forms.ChoiceField): 
    def clean(self, value): 
        return value


class Material(models.Model):
	lab = models.ForeignKey(Lab)
	code = models.CharField(max_length=5)
	name = models.CharField(max_length=300)
	tags = TagField()
	report = models.ForeignKey(Report)

	def __unicode__(self):
        	return self.name

	def get_tags(self):
        	return Tag.objects.get_for_object(self) 

class MyForm(forms.Form): 
    material = forms.ModelChoiceField(Material.objects, widget=forms.Select(attrs={'onchange':'FilterTests();'})) 
    test = DynamicChoiceField(widget=forms.Select(attrs={'disabled':'false'}), choices=(('-1','Select Tests'),))

class Test(models.Model):
	#lab = models.ForeignKey(Lab)
	material = models.ForeignKey(Material)
	code = models.CharField(max_length=5)
	name = models.CharField(max_length=300)
	quantity = models.IntegerField(blank=True, null=True)
	unit = models.CharField(max_length=15)
	cost = models.IntegerField(blank=True, null=True)
	tags = TagField()

	def __unicode__(self):
        	return self.name
	
	def get_tags(self):
        	return Tag.objects.get_for_object(self) 

class Clientadd(models.Model):
	user = models.ForeignKey(User)
	client = models.ForeignKey(UserProfile)
	
class Govt(models.Model):
	name =	models.CharField(max_length=600, blank=True )

	def __unicode__(self):
        	return self.name

class Payment(models.Model):
	name = models.CharField(max_length = 50,blank =True)

	def __unicode__(self):
        	return self.name

class Job(models.Model):
	"""
	**ClientJob**
	
	ClientJob Class is define all field required to submit detail about new Job.
	
	""" 
        client = models.ForeignKey(Clientadd)
	check_number = models.CharField(max_length=15,blank=True)
	check_dd_date = models.CharField(blank=True, max_length=15)
	job_no = models.IntegerField(editable =False)
	site = models.CharField(max_length=600, blank=True )
	type_of_work = models.ForeignKey(Govt)
	report_type = models.ForeignKey(Report)
	pay = models.CharField(max_length=600, blank=True )
	date = models.DateField(auto_now_add=True)

	def __unicode__(self):
          return self.id()


class JobForm(forms.ModelForm):
	class Meta :
		model = Job
		exclude= ['client','job_no','report_type','date']
               
	
class ClientJob(models.Model):
	job = models.ForeignKey(Job)
	material = models.ForeignKey(Material)
	test = models.ManyToManyField(Test)
	
	def __unicode__(self):
          return self.id()

class ClientJobForm(forms.ModelForm):
	class Meta :
		model = ClientJob
		exclude= ['job','material']


class SuspenceJob(models.Model):
	"""
	**SuspenceJob**
	
	SuspenceJob Class is used to define all fields required to submit detail about new Suspence Job.
	
	""" 
	job = models.ForeignKey(Job)
	field = models.ForeignKey(Material)
	test = models.ForeignKey(Test)
	other = models.CharField(max_length=600, blank=True )
	

	def __unicode__(self):
          return self.id()

class SuspenceJobForm(forms.ModelForm):
	class Meta :
		model = SuspenceJob
		exclude= ['job','field','test']

class TestTotal(models.Model):
	job_no = models.IntegerField(editable =False)
	mat = models.IntegerField(editable =True,null=True)
	unit_price = models.IntegerField(blank=True,null=True)
	type = models.CharField(max_length=100,blank=True,null=True)

	def __unicode__(self):
        	return self.id

class TestTotalForm(forms.ModelForm):
	class Meta :
		model = TestTotal

	
	
class Sessiondata(models.Model):
	amt = models.IntegerField(blank=True,null=True)


class TestsForm(ModelForm):

    tests = forms.ModelMultipleChoiceField(queryset=Test.objects.all(), required=False,widget=forms.CheckboxSelectMultiple)

    class Meta:
        model = ClientJob
	exclude = ('report_type','type_of_consultancy','field','client','date','site','type_of_work','letter_no','letter_date',)

    def __init__(self):
        super(TestsForm, self).__init__()
	id = ClientJob.objects.aggregate(Max('job_no'))
	maxid =id['job_no__max']
	field = Field.objects.all()
	client = ClientJob.objects.values_list('field_id',flat=True).filter(job_no = maxid)
        self.fields['tests'].queryset = Test.objects.filter(field_id = client)


class Bill(models.Model):
	job_no = models.IntegerField(primary_key=True, editable =False)
	education_tax = models.IntegerField(blank=True,null=True)
	higher_education_tax = models.IntegerField(blank=True,null=True)
	service_tax = models.IntegerField(blank=True,null=True)
	net_total = models.IntegerField(blank=True,null=True)
	price = models.IntegerField(blank=True,null=True)

class BillForm(ModelForm):
	class Meta :
		model = Bill

class Amount(models.Model):
	job_no = models.IntegerField(blank=True,null=True)
	college_income = models.IntegerField(blank=True, null=True)
	admin_charge = models.IntegerField(blank=True,null=True)
	consultancy_asst = models.IntegerField(blank=True,null=True)
	development_fund = models.IntegerField(blank=True,null=True)
	unit_price = models.IntegerField(blank=True,null=True)
	report_type = models.CharField(max_length=100,blank=True,null=True)
		
        def __unicode__(self):
          return self.id()



class AmountForm(ModelForm):
	class Meta :
		model = Amount

class CdfAmount(models.Model):
	job_no = models.IntegerField(primary_key=True, editable =False)
	date = models.DateField(default=datetime.date.today(), editable=False)
	lab = models.CharField(max_length=100)
	total = models.IntegerField()
	field = models.CharField(max_length=10)
	other_field = models.CharField(max_length=100,blank=True,null=True)
	report_type = models.CharField(max_length=20,editable=False)

class CdfAmountForm(ModelForm):
	class Meta :
		model = CdfAmount	
	
class Distance(models.Model):
    	job =models.IntegerField(editable =False)
    	sandy = models.DecimalField(max_digits=10, decimal_places=3)

class DistanceForm(ModelForm):
	class Meta :
		model = Distance
		exclude= ['job']
	
	def __unicode__(self):
        	return self.id



class Suspence(models.Model):
	job_no = models.IntegerField(blank=True, null=True)
	rate = models.IntegerField(null=True, blank=True)
	sus = models.ForeignKey(SuspenceJob)
	work_charge = models.IntegerField(null=True, blank=True)
	labour_charge = models.IntegerField( blank=True, null=True)
	boring_charge_external = models.IntegerField( blank=True, null=True)
	boring_charge_internal = models.IntegerField( blank=True, null=True)
	car_taxi_charge = models.IntegerField( blank=True, null=True)
	lab_testing_staff = models.CharField( max_length=90,blank=True)
	field_testing_staff =models.CharField( max_length=90,blank=True)
	test_date = models.DateField( blank=True, null=True)
	suspence_bill_no = models.IntegerField( blank=True, null=True)

class SuspenceForm(ModelForm):
	class Meta :
		model = Suspence


class Organisation(models.Model):
	name = models.CharField(max_length=50)
	address = models.CharField(max_length=150)
	phone = models.CharField(max_length=20)
	director = models.CharField(max_length=50) 
	logo_upload = models.ImageField(upload_to='logo')

	def __unicode__(self):
        	return self.name

class Department(models.Model):
	organisation = models.ForeignKey(Organisation)
	name = models.CharField(max_length=50)
	address = models.CharField(max_length=150)
	phone = models.CharField(max_length=20)
	dean = models.CharField(max_length=50)
	faxno = models.IntegerField( blank=True, null=True)

	def __unicode__(self):
        	return self.name

class Staff(models.Model):
	department = models.ForeignKey(Department)
	code = models.CharField(max_length=5)
	name = models.CharField(max_length=50)
	daily_income = models.IntegerField(blank=True)
	position = models.CharField(max_length=15)
	lab = models.ForeignKey(Lab)

tcc/forms.py
from django import forms
from Automation.tcc.models import *

class SuspenceClearence(forms.Form):
	"""
	Suspence Clearence Form for adding extra Charges. 
	"""
	job_no = forms.IntegerField()
	labour_charge = forms.IntegerField(initial= '0')
	car_taxi_charge = forms.IntegerField(initial= '0')
	boring_charge_external = forms.IntegerField(initial= '0')
	boring_charge_internal = forms.IntegerField(initial= 0)
	lab_testing_staff = forms.CharField(max_length = 20)
	field_testing_staff = forms.CharField(max_length = 20,required=False)

templates/tcc/add_job.html
{% extends "base.html" %}
{% load i18n %}
<html>

<head>
    <title>Gndec Ludhiana</title>
	
</head>

{% block content %}
<script type="text/javascript" >
    function showfield(name){
    if(name=='cheque' || 'dd')document.getElementById('div1').style.display="block";
    else document.getElementById('div1').style.display="none";
    }
    function hidefield() {
    document.getElementById('div1').style.display='none';
    }
    
    </script>
<h1>Add Lab Job</h1>
 <table>
<tr><td><label for="id_search">Type of work:</label></td><td><select name="form" ONCHANGE="location =
this.options[this.selectedIndex].value;">
	 <option value="">Select type</option>
{% for reports in report %}
  <option value="http://localhost/automation/tcc11_12/select/?id={{reports.id}}">{{reports.name}}</option>
	{% endfor %}
</select></tr>
<br>
 <tr><td><label for="id_search">Material:</label></td><td><select name="form" ONCHANGE="location =
this.options[this.selectedIndex].value;">
	<option value="">Select Material</option>
{% for field in field_list %}
  <option value="http://localhost/automation/tcc11_12/save/?q={{field.id}}">{{field.name}}</option>
	{% endfor %}
</select></td></tr>
<tr><td><b><center><a href="http://localhost/automation/tcc11_12/map" >Mark site on map</a> </td></tr>
 
<br>
    {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
    {% endif %}

    <form action="" method="post">
	{% csrf_token %}
          
	<tr><td><label for="id_site">Complete Adress of Map:</label></td><td><input id="id_site" type="site" name="site"  maxlength="600" /></td></tr>
	
			
{% if test %}
       {% for tests in test%}
        	   
		 <tr><td><label for="check">Test:</label></td><td> <input type="checkbox" name="test" value="{{tests.id}}">
		 <label for="check">{{ tests.name }}</label><br /></td></tr>

		
       {% endfor %}      
       {% endif  %}
	
	<tr><td><label for="id_work">Type of Work:</label></td><td><select name="type_of_work">
{% for typeofwork in work %}
    <option value="{{typeofwork.id }}">{{ typeofwork.name }}</option>
{% endfor %}
</select></td></tr>
	
<tr><td><label for="id_pay">Mode of Payment:</label></td><td>
<select name="pay" id="pay" onchange="showfield(this.options[this.selectedIndex].value)">
<option value="">---</option>
<option value="CASH">Cash</option>
<option value="ONLINE">Online</option>
<option value="cheque" >Cheque</option>
<option value="dd" >DD</option>
</select></td></tr> </table>
<div id="div1" style="display:none">Enter Cheque/DD No. : <input type="text" name="check_number" /> </br>Enter Cheque/DD Date : <input type="text" name="check_dd_date" /> </div>

       
        <input type="submit" value="Submit">
    </form>
</html>
{% endblock %}

templates/tcc/bill.html
<html>
<head>
<link rel="stylesheet" type="text/css" href="a.css" /><title>Report</title></head>
<div style="font-size:20px" align='center'><b>{{address.name}}</b></div>
<div style="font-size:15px" align='center'>gill road, Ludhiana</div>
<div style="font-size:20px" align='center'>{{title.name}}</div><br>
<div align='left'>STC No. G31843A(S)LDH -ST-001<br>PAN No. AAATN1978L</div>
<br>
<body>

<br/><h2 align="center">BILL</h2>

<div align="left">No. : GNDEC/TCC/B/{{ job_no }}</div>
<br/><br/>

<div align="left">To<br> {{ clients.name }}</div>

<br/><br/>

<div align= "left">
	<table border="1" width="100%">
		<tr>
			<td>Details</td>
			<td>Per. </td>
			<td>Rate</td>
			<td>Amount</td>
		</tr>
		<tr><td>Charges For {% for mates in mate %}
		    {% for prices in price %}
			 {{ mates.name}} ({{ prices.unit_price}}). 
			{% endfor%}
			{% endfor%}</td>
			<td rowspan="6"></td>
			<td rowspan="6"></td>
			<td align="right" rowspan="2">{{ bill.price }}.00</td>
		</tr>
		<tr>
			
			<td>Site :{% for jobs in job %} {{ jobs.site}}.{% endfor%}</td>
			
		</tr>
		<tr>
			<td>Service Tax  @ {{ servicetaxprint }}% </td>
			<td  align="right">{{ bill.service_tax }}.00</td>
		<tr>
			<td>Education Cess  @ {{ educationtaxprint }}% </td>
			<td  align="right">{{ bill.education_tax }}.00</td>
		</tr>
		<tr>
			<td>Higher Education Cess  @ {{ highereducationtaxprint }}% </td>
			<td  align="right">{{ bill.higher_education_tax }}.00</td>
		</tr>
		<tr>
				<td>Total Rs.  ( {{ net_total_eng }} only) </td>
			<td  align="right">{{ cdftotal }} {{ bill.net_total}}.00</td>
		</tr>	
	</table>
<br/><br/><br/><br/><br/>
<div align="right">DEAN</div>
</body>
</html>

templates/tcc/checktest.html
{% extends "base.html" %}
{% load i18n %}
<html>
<head>
    <title>Gndec Ludhiana</title>
</head>
{% block content %}
<br>
    {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
    {% endif %}

    <form action="" method="post">
	{% csrf_token %}
<table>
            {{ form.as_table }}
        </table>
        <!--{% for test in tests %}
<table>
            {{ form.as_table }}
        </table>
 <input type="checkbox" name="test" id="{{test.id}}" value={{test.name}} />
<label for="{{test.id}}"><b>{{test.name}}</b></label><br />

{% endfor %}-->

        <input type="submit" value="Submit">
    </form>

</html>
{% endblock %}

templates/tcc/dynamicdrop1.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
    <head>
        <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
        <title>Update Drop-Down Without Refresh</title>
        <script type="text/javascript" charset="utf-8">
            function FilterModels() {
                var materialist = document.getElementById('material');
                var testlist = document.getElementById('tests');
		var seltest = "{{test.material_id}}"
		var materials_id = materiallist.value;
		alert(materials_id);
                var material_id = materiallist.options[materiallist.selectedIndex].value;
		}
		function debug()
		{
			alert("debug working");
		}
			
                /*var modelstxt = new Array();
                modelstxt[1] = "1\tEscort\n2\tTaurus";
                modelstxt[2] = "1\tAltima\n2\tMaxima";
                var models = modelstxt[make_id].split("\n");
                for (var count = modelslist.options.length-1; count >-1; count--){
                    modelslist.options[count] = null;
                }
                for (i=0; i<models.length; i++){
                    var modelvals = models[i].split("\t");
                    var option = new Option(modelvals[1], modelvals[2], false, false);
                    modelslist.options[modelslist.length] = option;
                }
            }*/
        </script>
    </head>
    <body>
        <p>This is a proof of concept to update a select (drop-down) list of values, based on the selection of another select (drop-down) element using ajax.</p>
        <form action="" method="get" accept-charset="utf-8">
            <select name="material" onchange="FilterModels()" id="material">
                <option>--</option>
                 {% for materials in material %}
            <option value="{{ materials.id}}">{{ materials.name }}</option>
        {% endfor %}
            </select>
		
            <select name="tests" id="tests">
                <option>Choose test</option>
		
            </select>
        </form>
    </body>
</html>

templates/tcc/fulldetail.html
<link rel="stylesheet" type="text/css" href="{{ MEDIA_URL }}/profile/css/souvenir.css" />
<script type="text/javascript" src="{{ MEDIA_URL }}/profile/css/tablecloth/tablecloth/tablecloth.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}/profile/css/gs_sortable.js"></script>
<script type="text/javascript">
<!--
var TSort_Data = new Array ('my_table','','', 's', 'i', 's');
tsRegister();
// -->
</script> 
<table id="my_table"> 
<caption>SOUVENIR RECORD</caption>
<thead><tr><th>SR.No<th>PHOTO<th>NAME<th>ROLL NO<th>BRANCH</tr></thead>

{% if fulldetail  %}
    {% for part in fulldetail %}
        {% if part.firstname %}
        <tr><td>{% if y %} y {% endif %} </td><td>{% if part.photo %} <img src="{{ part.photo.url }}" height="50" />{% endif %}<td><a href="{{IP_ADDRESS}}/django/souvenir/detail/?class_roll_no={{ part.class_roll_no}}" >{{ part.firstname }} {{ part.middlename }} {{ part.lastname }}</a><td>{{ part.class_roll_no}}</a> <td>{{ part.branch }}</tr>
{% endif %}
    {% endfor %}
    
{% else %}
    <p> Data is Not available.</p>
{% endif %}
</td></tr>
</table>

templates/tcc/map.html
{% extends "base.html" %}
{% load i18n %}
<html>
<head>
    <title>gne</title>
</head>
{% block content %}

{{ form.map }}
{{ form.media.js }}

</html>
{% endblock %}

templates/tcc/new_client_ok.html
{% extends "base.html" %}
{% load i18n %}

<html>
<head>
    <title>Gndec Ludhiana</title>
</head>
{% block content %}
<body>
Thanks, for Adding Client <br/>
<br/><br/>
Want to add job for this client ?<br/>
<a href="{{ LOCAL_URL }}/automation/tcc11_12/addjob/?id={{maxid}}" >Add Job</a> </td>
	
</table>


</body>
{% endblock %}

templates/tcc/receipt.html
<html>
<head><title>Receipt</title></head>
<center><h3><b>RECEIPT</h3>  </b></center>
<br/>


<div align="left"> Receipt No. : {{job_no}}</div>
<br/><br/><br/>

{% for totals in total %}
<div align="left">Received a sum of Rs.{{totals.net_total}} (Rupees  {{ net_total_eng }}only) from  <i> {{ clients}} by {% for jobs in job %}{{ jobs.pay}}{% endfor %} {{suspence.type}} {{ suspence.check_number}}
 {{suspence.check_dd_date }} on account of {% for mates in mate %}
{{mates.name}}{% endfor %}.</div>

{% endfor %}
<br/><br/>
<div align="right"><b> Cashier</b></div>
<br>
<br>
</body>
</html>

templates/tcc/report.html
<html>
<head><title>Report</title></head>
<body>
<br>

<div style="position:absolute;right:7px;top:55px;">Main/Mat. No :<u>{{ job_no }}</u> </div>
<div style="position:absolute;right:7px;top:75px;">Dated :  </div>
<div style="position:absolute;left:7px;top:105px;">Director,</div>
<br/> <br/><br/><br/><br></br>
Received a sum of Rs. {{amount.unit_price }}/- ( Rupees {{ net_total_eng }} only ) <br/><br>
Vide Cash from : {{ cli }} <br><br>
On account of : testing/checking {{ mate.name }} <br/><br>
<div style="position:absolute;left:7px;top:270px;">Vide Receipt No. : {{job_no }}  Dated: </div>
<div style="position:absolute;left:7px;top:290px;">Nature of Consultancy :{{ client.type }},  Ratio {{ ratio1 }}:{{ ratio2 }} </div>
<div align= "left">
<br/><br/><br/></br>
<table border="1" width="100%">
<tr>
	<td colspan="3">THE DISTRIBUTION MAY BE MADE AS</td>
</tr>

  
<tr>
	<td rowspan="9">CREDITS</td>
	<td>COLLEGE INCOME {{ collegeincome }}% </td>
	<td  align="right">{{ amount.college_income }}.00</td>
</tr>
<tr>
	<td>ADMN. CHARGES {{ admincharge }}% </td>
	<td  align="right">{{ amount.admin_charge }}.00</td>
</tr>
<tr>
	<td>CONSULTANCY ASST. </td>
	<td  align="right">{{ amount.consultancy_asst }}.00</td>
</tr>
<tr>
	<td>DEV. FUND (CONSULTANCY) </td>
	<td  align="right">{{ amount.development_fund }}.00</td>
</tr>
<tr>
	<td>TOTAL (Rs.) </td>
	<td  align="right">{{ amount.unit_price }}.00</td>
</tr>
</table>
</div>
<br>
<br>
<div>
<table border="1" width="100%">
<tr>
	<td colspan="3"></TD>
</TR>
<tr>
	<TD>NAME OF EMPLOYEES</TD>
	<TD>DESIGNATION</TD>
</tr>
{% if staff  %}
    {% for part in staff %}
<tr>
	
	<TD> {{ part.name }}</TD>
	<td> {{ part.position }}</TD>
</tr>
	{% endfor %}
{% endif %}
</TABLE>
</div>
<div align="left">THE WORK HAS BEEN EXECUTED BY ABOVE PERSONS AS MENTIONED ABOVE. </div>
<br>
<div>(Supdt. Accounts)</div><div align="right">DEAN</div><br>
<div align="left">
Account Clerk (Consultancy)</div>

</body>
</html>

templates/tcc/sandy.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
    <head>
        <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
        <title>Update Drop-Down Without Refresh</title>
        <script type="text/javascript" charset="utf-8">
            function FilterModels() {
                var makeslist = document.getElementById('makes');
                var modelslist = document.getElementById('models');
                var make_id = makeslist.options[makeslist.selectedIndex].value;
                var modelstxt = new Array();
                modelstxt[1] = "1\tEscort\n2\tTaurus";
                modelstxt[2] = "1\tAltima\n2\tMaxima";
                var models = modelstxt[make_id].split("\n");
                for (var count = modelslist.options.length-1; count >-1; count--){
                    modelslist.options[count] = null;
                }
                for (i=0; i<models.length; i++){
                    var modelvals = models[i].split("\t");
                    var option = new Option(modelvals[1], modelvals[2], false, false);
                    modelslist.options[modelslist.length] = option;
                }
            }
        </script>
    </head>
    <body>
        <p>This is a proof of concept to update a select (drop-down) list of values, based on the selection of another select (drop-down) element using ajax.</p>
        <form action="" method="get" accept-charset="utf-8">
            <select name="makes" onchange="FilterModels()" id="makes">
                <option>--</option>
                <option value="1">Ford</option>
                <option value="2">Nissan</option>
            </select>
            <select name="models" id="models">
                <option>Choose Make</option>
            </select>
        </form>
    </body>
</html>

templates/tcc/save_job.html
{% extends "base.html" %}
{% load i18n %}

<html>
<head>
    <title>Gndec Ludhiana</title>
</head>
{% block content %}
<body>

site is {{place}} <br/>
<br/><br/>
tests are {{test}}
	
</table>


</body>
{% endblock %}